// Seed data for demo mode. None of this touches the real server.

export const DEMO_CONFIG_OVERLAY = {
  serverPath: '/home/minecraft/server',
  rconHost: '127.0.0.1',
  rconPort: 25575,
  minecraftVersion: '1.20.1',
  modsFolder: 'mods',
  disabledModsFolder: 'mods_disabled',
};

// --- Server status ---
export function getDemoStatus(running, uptime) {
  return {
    running,
    uptime,
    rconConnected: running,
    onlineCount: running ? 3 : 0,
    serverPath: '/home/minecraft/server',
    minecraftVersion: '1.20.1',
    demoMode: true,
  };
}

// --- Online players ---
export const DEMO_ONLINE_PLAYERS = ['Steve', 'Alex', 'CreeperSlayer99'];

// --- Operators ---
export const DEMO_OPS = [
  { uuid: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', name: 'Steve', level: 4, bypassesPlayerLimit: true },
  { uuid: 'b2c3d4e5-f6a7-8901-bcde-f12345678901', name: 'Alex', level: 3, bypassesPlayerLimit: false },
  { uuid: 'c3d4e5f6-a7b8-9012-cdef-123456789012', name: 'CreeperSlayer99', level: 2, bypassesPlayerLimit: false },
];

// --- Whitelist ---
export const DEMO_WHITELIST = [
  { uuid: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', name: 'Steve' },
  { uuid: 'b2c3d4e5-f6a7-8901-bcde-f12345678901', name: 'Alex' },
  { uuid: 'c3d4e5f6-a7b8-9012-cdef-123456789012', name: 'CreeperSlayer99' },
  { uuid: 'd4e5f6a7-b8c9-0123-defa-234567890123', name: 'DiamondDigger' },
  { uuid: 'e5f6a7b8-c9d0-1234-efab-345678901234', name: 'NightOwl_MC' },
];

// --- Usercache (all players who have ever joined) ---
export const DEMO_USERCACHE = [
  {
    name: 'Steve',
    uuid: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    expiresOn: '2027-01-15 10:30:00 +0000',
    lastSeen: '2026-03-21T10:30:00Z',
    firstSeen: '2025-06-15T14:00:00Z',
  },
  {
    name: 'Alex',
    uuid: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    expiresOn: '2027-01-14 08:15:00 +0000',
    lastSeen: '2026-03-21T08:15:00Z',
    firstSeen: '2025-07-20T09:00:00Z',
  },
  {
    name: 'CreeperSlayer99',
    uuid: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    expiresOn: '2027-01-13 22:45:00 +0000',
    lastSeen: '2026-03-20T22:45:00Z',
    firstSeen: '2025-09-01T16:30:00Z',
  },
  {
    name: 'DiamondDigger',
    uuid: 'd4e5f6a7-b8c9-0123-defa-234567890123',
    expiresOn: '2027-01-10 16:00:00 +0000',
    lastSeen: '2026-03-18T16:00:00Z',
    firstSeen: '2025-11-10T20:00:00Z',
  },
  {
    name: 'NightOwl_MC',
    uuid: 'e5f6a7b8-c9d0-1234-efab-345678901234',
    expiresOn: '2027-01-08 03:20:00 +0000',
    lastSeen: '2026-03-15T03:20:00Z',
    firstSeen: '2025-12-01T23:00:00Z',
  },
  {
    name: 'Griefer99',
    uuid: 'f6a7b8c9-d0e1-2345-fabc-456789012345',
    expiresOn: '2026-06-01 14:22:00 +0000',
    lastSeen: '2026-01-05T14:22:00Z',
    firstSeen: '2025-12-28T10:00:00Z',
  },
  {
    name: 'BuilderBob',
    uuid: '12345678-abcd-ef01-2345-6789abcdef01',
    expiresOn: '2026-12-20 11:00:00 +0000',
    lastSeen: '2026-03-10T11:00:00Z',
    firstSeen: '2025-08-15T12:00:00Z',
  },
  {
    name: 'RedstoneQueen',
    uuid: '23456789-bcde-f012-3456-789abcdef012',
    expiresOn: '2026-11-05 19:30:00 +0000',
    lastSeen: '2026-02-20T19:30:00Z',
    firstSeen: '2025-10-05T18:00:00Z',
  },
];

// --- Bans ---
export const DEMO_BANS = {
  players: [
    {
      uuid: 'f6a7b8c9-d0e1-2345-fabc-456789012345',
      name: 'Griefer99',
      source: 'Steve',
      reason: 'Griefing spawn area',
      created: '2025-12-01T14:22:00Z',
      expires: 'forever',
    },
    {
      uuid: 'a7b8c9d0-e1f2-3456-abcd-567890123456',
      name: 'SpamAccount',
      source: 'Manager',
      reason: 'Chat spam / bot',
      created: '2026-01-15T09:10:00Z',
      expires: 'forever',
    },
  ],
  ips: [],
};

// --- server.properties ---
export const DEMO_PROPERTIES = {
  'enable-rcon': 'true',
  'rcon.port': '25575',
  'rcon.password': '(hidden in demo)',
  'white-list': 'true',
  'online-mode': 'true',
  'max-players': '8',
  'server-port': '25565',
  motd: 'A Forge Modpack Server',
  gamemode: 'survival',
  difficulty: 'normal',
  'level-name': 'world',
  pvp: 'true',
  'spawn-protection': '16',
  'op-permission-level': '4',
  'view-distance': '10',
  'simulation-distance': '8',
  'allow-flight': 'true',
  'spawn-monsters': 'true',
  'spawn-animals': 'true',
  'spawn-npcs': 'true',
  'enable-command-block': 'false',
  'level-type': 'minecraft:normal',
  'generate-structures': 'true',
  'max-world-size': '29999984',
};

// --- Helpers ---
// Fallback CDN icon URL — used until enrichDemoIcons() fetches the real URLs.
// The actual format (png/webp) varies per project; enrichment corrects this at startup.
const cdn = (id) => `https://cdn.modrinth.com/data/${id}/icon.png`;

// M builds an installed mod entry. projectId (optional) is the Modrinth project ID.
const M = (
  filename,
  size,
  enabled,
  title,
  desc,
  clientSide,
  serverSide,
  version,
  slug,
  projectId = null,
  author = null,
) => ({
  filename,
  size,
  enabled,
  _projectId: projectId, // retained for icon enrichment; not sent to the browser
  modrinthData: {
    projectTitle: title,
    projectDescription: desc,
    clientSide,
    serverSide,
    versionNumber: version,
    projectSlug: slug,
    iconUrl: projectId ? cdn(projectId) : null,
    author,
    // Fake but plausible engagement numbers for demo display purposes
    downloads: Math.round(size * 0.4) + 500_000,
    follows: Math.round(size * 0.003) + 3_000,
  },
});

// --- Installed mods (server-compatible Forge 1.20.1 mods only) ---
// Project IDs sourced from Modrinth; used for CDN icon URLs.
export const DEMO_MODS = [
  M(
    'jei-1.20.1-forge-15.3.0.4.jar',
    1_241_800,
    true,
    'Just Enough Items',
    'A recipe and item viewing mod.',
    'required',
    'optional',
    '15.3.0.4',
    'jei',
    'u6dRKJwZ',
    'mezz',
  ),
  M(
    'appliedenergistics2-15.2.1.jar',
    7_483_200,
    true,
    'Applied Energistics 2',
    'A mod about Matter, Energy, and using them.',
    'required',
    'required',
    '15.2.1',
    'ae2',
    'XxWD5pD3',
    'yueh',
  ),
  M(
    'create-1.20.1-0.5.1.f.jar',
    11_204_100,
    true,
    'Create',
    'Aesthetic tech and automation using rotational force.',
    'required',
    'required',
    '0.5.1.f',
    'create',
    'LNytGWDc',
    'simibubi',
  ),
  M(
    'thermal_expansion-1.20.1-10.6.0.jar',
    4_921_500,
    true,
    'Thermal Expansion',
    'Expansion of the Thermal Series.',
    'required',
    'required',
    '10.6.0',
    'thermal-expansion',
    'hmD6rrUJ',
    'TeamCoFH',
  ),
  M(
    'Mekanism-1.20.1-10.4.7.19.jar',
    14_832_700,
    true,
    'Mekanism',
    'High-tech machinery and tools.',
    'required',
    'required',
    '10.4.7.19',
    'mekanism',
    'Ce6I4WUE',
    'bradyaidanc',
  ),
  M(
    'Botania-1.20.1-445.jar',
    6_341_000,
    true,
    'Botania',
    'A tech mod themed around natural magic.',
    'required',
    'required',
    '445',
    'botania',
    'pfjLUfGv',
    'Vazkii',
  ),
  M(
    'immersiveengineering-1.20.1-10.1.0.jar',
    9_128_300,
    true,
    'Immersive Engineering',
    'A retro-futuristic tech mod with multiblocks.',
    'required',
    'required',
    '10.1.0',
    'immersiveengineering',
    'tIm2nV03',
    'BluSunrize',
  ),
  M(
    'TConstruct-1.20.1-3.8.4.272.jar',
    5_673_400,
    true,
    "Tinkers' Construct",
    'Tool and weapon crafting with materials.',
    'required',
    'required',
    '3.8.4.272',
    'tinkers-construct',
    'rxIIYO6c',
    'boni',
  ),
  M(
    'StorageDrawers-1.20.1-12.0.2.jar',
    1_892_600,
    true,
    'Storage Drawers',
    'Multi-drawer storage blocks.',
    'required',
    'required',
    '12.0.2',
    'storagedrawers',
    'guitPqEi',
    'jaquadro',
  ),
  M(
    'ironchest-1.20.1-14.4.4.jar',
    734_900,
    true,
    'Iron Chests',
    'Bigger and better chests.',
    'required',
    'required',
    '14.4.4',
    'iron-chests',
    'P3iIrPH3',
    'progwml6',
  ),
  M(
    'Waystones-1.20.1-forge-14.1.3.jar',
    1_243_100,
    true,
    'Waystones',
    'Teleportation waystone blocks.',
    'required',
    'required',
    '14.1.3',
    'waystones',
    'LOpKHB2A',
    'BlayTheNinth',
  ),
  M(
    'farmersdelight-1.20.1-1.2.3.jar',
    2_134_600,
    true,
    "Farmer's Delight",
    'Expands farming and cooking.',
    'required',
    'required',
    '1.2.3',
    'farmers-delight',
    'R2OftAxM',
    'vectorwing',
  ),
  M(
    'alexsmobs-1.22.7.jar',
    8_942_300,
    true,
    "Alex's Mobs",
    'Adds many unique mobs to the game.',
    'required',
    'required',
    '1.22.7',
    'alexs-mobs',
    '2cMuAZAp',
    'sbom_4',
  ),
  M(
    'biomesoplenty-1.20.1-18.0.0.596.jar',
    5_218_400,
    true,
    "Biomes O' Plenty",
    'Adds a ton of new biomes.',
    'required',
    'required',
    '18.0.0.596',
    'biomes-o-plenty',
    'HXF82T3G',
    'Forstride',
  ),
  M(
    'Quark-4.0-460.jar',
    4_103_700,
    true,
    'Quark',
    'Small tweaks and improvements to vanilla.',
    'required',
    'required',
    '4.0-460',
    'quark',
    'qvIfYCYJ',
    'Vazkii',
  ),
  M(
    'supplementaries-1.20.1-2.8.14.jar',
    3_847_200,
    true,
    'Supplementaries',
    'Decorative blocks and items.',
    'required',
    'required',
    '2.8.14',
    'supplementaries',
    'fFEIiSDQ',
    'MehVahdJukaar',
  ),
  M(
    'sophisticated-storage-1.20.1-0.9.14.jar',
    2_341_600,
    true,
    'Sophisticated Storage',
    'Upgradeable tiered chests and barrels with filter, sort, and auto-deposit upgrades.',
    'required',
    'required',
    '0.9.14',
    'sophisticated-storage',
    'hMlaZH8f',
    'P3pp3rF1y',
  ),
  M(
    'lootr-0.7.35.80.jar',
    389_400,
    true,
    'Lootr',
    'Unique loot for each player in chests.',
    'unsupported',
    'required',
    '0.7.35.80',
    'lootr',
    'EltpO5cN',
    'Noobanidus',
  ),
  M(
    'spark-1.10.73-forge.jar',
    923_600,
    true,
    'spark',
    'Performance profiler for the server.',
    'optional',
    'required',
    '1.10.73',
    'spark',
    'Wnxd13zP',
    'lucko',
  ),
  M(
    'gravestones-1.20.1-1.0.17.jar',
    891_300,
    true,
    'Gravestones',
    'Stores your items in a grave when you die. Recoverable via tombstone block.',
    'required',
    'required',
    '1.0.17',
    'gravestones',
    'ssUbhMkL',
    'MaxHyper',
  ),
  // Disabled mods
  M(
    'configured-2.2.3-1.20.1.jar',
    241_100,
    false,
    'Configured',
    'In-game mod config editor.',
    'optional',
    'optional',
    '2.2.3',
    'configured',
    'HlpEBg3R',
    'MrCrayfish',
  ),
  M(
    'flan-1.20.1-1.9.1.jar',
    634_700,
    false,
    'Flan',
    'Chunk claiming and land protection with team support.',
    'required',
    'required',
    '1.9.1',
    'flan',
    'Si383TIH',
    'Flemmli98',
  ),
];

// --- Console log simulation ---
export const DEMO_STARTUP_LOGS = [
  '[00:00:00] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20a69 starting: java version 17.0.9 by Eclipse Adoptium',
  '[00:00:00] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: JVM identified as Java 17 HotSpot VM by Eclipse Adoptium',
  '[00:00:01] [main/INFO] [ne.mi.fm.lo.LoadingModList/]: Forge mod loading, 204 mods to load',
  '[00:00:02] [main/INFO] [ne.mi.fm.lo.ModLoader/]: Loading mod: forge@47.3.0',
  '[00:00:02] [main/INFO] [ne.mi.fm.lo.ModLoader/]: Loading mod: minecraft@1.20.1',
  '[00:00:03] [main/INFO] [ne.mi.fm.lo.ModLoader/]: Loading mod: jei@15.3.0.4',
  '[00:00:03] [main/INFO] [ne.mi.fm.lo.ModLoader/]: Loading mod: create@0.5.1.f',
  '[00:00:04] [main/INFO] [ne.mi.fm.lo.ModLoader/]: Loading mod: mekanism@10.4.7.19',
  '[00:00:05] [main/INFO] [ne.mi.fm.lo.ModLoader/]: Loading mod: ae2@15.2.1',
  '[00:00:06] [main/INFO] [ne.mi.fm.lo.ModLoader/]: Loading mod: botania@445',
  '[00:00:07] [ForkJoinPool-1-worker-3/INFO] [ne.mi.fm.lo.ModLoader/]: Parallel mod loading: 200 mods',
  '[00:00:09] [Forge Version Check/INFO] [ne.mi.forge.VersionChecker/]: [create] Starting version check at https://maven.tterrag.com/...',
  '[00:00:12] [Worker-Main-1/INFO] [ne.mi.re.GameData/REGISTRIES]: Registering blocks for create',
  '[00:00:15] [Worker-Main-1/INFO] [ne.mi.re.GameData/REGISTRIES]: Registering items for mekanism',
  '[00:00:18] [Worker-Main-1/INFO] [ne.mi.re.GameData/REGISTRIES]: Registering entities for alexsmobs',
  '[00:00:23] [Server thread/INFO] [ne.mi.co.se.GameTestServer/]: Starting server',
  '[00:00:24] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.20.1',
  '[00:00:24] [Server thread/INFO] [minecraft/DedicatedServer]: Loading properties',
  '[00:00:24] [Server thread/INFO] [minecraft/MinecraftServer]: Default game type: SURVIVAL',
  '[00:00:24] [Server thread/INFO] [minecraft/MinecraftServer]: Generating keypair',
  '[00:00:25] [Server thread/INFO] [minecraft/MinecraftServer]: Starting Minecraft server on *:25565',
  '[00:00:25] [Server thread/INFO] [minecraft/MinecraftServer]: Using epoll channel type',
  '[00:00:26] [Server thread/INFO] [ne.mi.fm.co.FMLCommonSetupEvent/]: FML Setup: loading complete',
  '[00:00:28] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing level "world"',
  '[00:00:30] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for dimension minecraft:overworld',
  '[00:00:31] [Worker-Main-1/INFO] [minecraft/ChunkMap]: Preparing spawn area: 0%',
  '[00:00:33] [Worker-Main-1/INFO] [minecraft/ChunkMap]: Preparing spawn area: 42%',
  '[00:00:35] [Worker-Main-1/INFO] [minecraft/ChunkMap]: Preparing spawn area: 89%',
  '[00:00:37] [Server thread/INFO] [minecraft/MinecraftServer]: Time elapsed: 37224 ms',
  '[00:00:37] [Server thread/INFO] [minecraft/DedicatedServer]: Done (37.224s)! For help, type "help"',
  '[00:00:37] [Server thread/INFO] [minecraft/MinecraftServer]: Starting RCON on 0.0.0.0:25575',
  '[Manager] Server ready. RCON connected.',
];

export const DEMO_ACTIVITY_LOGS = [
  '[Server thread/INFO] [minecraft/PlayerList]: Steve[/127.0.0.1:51234] logged in with entity id 412 at (128.5, 68.0, -204.3)',
  '[Server thread/INFO] [minecraft/MinecraftServer]: Steve joined the game',
  '[Server thread/INFO] [minecraft/MinecraftServer]: <Steve> hey guys',
  '[Server thread/INFO] [minecraft/PlayerList]: Alex[/192.168.1.5:55210] logged in with entity id 413 at (0.5, 64.0, 0.5)',
  '[Server thread/INFO] [minecraft/MinecraftServer]: Alex joined the game',
  '[Server thread/INFO] [minecraft/MinecraftServer]: <Alex> what are we building today',
  '[Server thread/INFO] [minecraft/MinecraftServer]: <Steve> working on the AE2 autocrafting setup',
  '[Server thread/INFO] [minecraft/DedicatedServer]: Saving the game (this may take a moment!)',
  '[Server thread/INFO] [minecraft/MinecraftServer]: Saved the game',
  '[Server thread/INFO] [minecraft/MinecraftServer]: <Alex> CreeperSlayer want to come help?',
  '[Server thread/INFO] [minecraft/PlayerList]: CreeperSlayer99[/192.168.1.7:60001] logged in with entity id 501 at (310.2, 72.0, 88.9)',
  '[Server thread/INFO] [minecraft/MinecraftServer]: CreeperSlayer99 joined the game',
  '[Server thread/INFO] [minecraft/MinecraftServer]: <CreeperSlayer99> omw',
  "[Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 2100ms or 42 ticks behind",
  '[Server thread/INFO] [minecraft/MinecraftServer]: <Steve> anybody need iron?',
  '[Server thread/INFO] [minecraft/DedicatedServer]: Saving the game (this may take a moment!)',
  '[Server thread/INFO] [minecraft/MinecraftServer]: Saved the game',
  '[Server thread/INFO] [minecraft/MinecraftServer]: CreeperSlayer99 left the game',
  '[Server thread/INFO] [minecraft/MinecraftServer]: <Alex> gg',
];

// --- Paginated browse list shown by default in the Browse Modrinth tab ---
const B = (project_id, slug, title, description, author, client_side, server_side, downloads, follows, categories) => ({
  project_id,
  slug,
  title,
  description,
  author,
  client_side,
  server_side,
  downloads,
  follows,
  icon_url: cdn(project_id),
  versions: ['1.20.1', '1.20'],
  categories,
});

// Browse results show mostly mods NOT yet installed, so users see what they can add.
// Three already-installed mods are included (marked with *) to demonstrate the
// "Installed" badge and disabled Install button in the UI.
export const DEMO_BROWSE_RESULTS = {
  hits: [
    B(
      'u6dRKJwZ',
      'jei',
      'Just Enough Items (JEI)',
      'View all items and recipes. Built from the ground up for stability and performance.',
      'mezz',
      'required',
      'optional',
      87_543_219,
      12_847,
      ['forge', 'utility'],
    ), // * installed
    B(
      'lfHFW1mp',
      'journeymap',
      'JourneyMap',
      'Real-time map in-game or in a web browser as you explore. Works in singleplayer and multiplayer.',
      'techbrew',
      'required',
      'optional',
      66_112_834,
      14_203,
      ['forge', 'utility'],
    ),
    B(
      'LNytGWDc',
      'create',
      'Create',
      'Aesthetic tech and automation using rotational force. Build elaborate contraptions and automated factories.',
      'simibubi',
      'required',
      'required',
      62_384_001,
      28_441,
      ['forge', 'technology'],
    ), // * installed
    B(
      '1bokaNcj',
      'xaeros-minimap',
      "Xaero's Minimap",
      "Displays a minimap on your HUD. Compatible with Xaero's World Map for full mapping support.",
      'xaero96',
      'required',
      'optional',
      54_887_002,
      11_330,
      ['forge', 'utility'],
    ),
    B(
      'LOpKHB2A',
      'waystones',
      'Waystones',
      'Fast travel via waystone blocks. Place stones in your world and teleport between them.',
      'BlayTheNinth',
      'required',
      'required',
      58_221_093,
      8_632,
      ['forge', 'utility'],
    ), // * installed
    B(
      'TyCTlI4b',
      'sophisticated-backpacks',
      'Sophisticated Backpacks',
      'Highly configurable backpacks with upgrade slots for sorting, refilling, and auto-picking.',
      'P3pp3rF1y',
      'required',
      'required',
      47_832_441,
      9_105,
      ['forge', 'utility'],
    ),
    B(
      'U6GY0xp0',
      'alexs-caves',
      "Alex's Caves",
      'Adds 8 unique underground biomes, each with new mobs, blocks, and resources to discover.',
      'sbom_4',
      'required',
      'required',
      43_218_770,
      18_554,
      ['forge', 'world-generation'],
    ),
    B(
      'C95ReXie',
      'mystical-agriculture',
      'Mystical Agriculture',
      'Grow almost any resource from seeds, including ores, gems, and mob drops. Fully configurable.',
      'BlakeBr0',
      'required',
      'required',
      41_002_119,
      7_841,
      ['forge', 'technology'],
    ),
    B(
      'e0bNACJD',
      'serene-seasons',
      'Serene Seasons',
      'Adds dynamic seasons that change the world around you — spring blossoms, summer heat, autumn leaves, winter snow.',
      'TheAdubbz',
      'required',
      'required',
      39_774_882,
      8_223,
      ['forge', 'world-generation'],
    ),
    B(
      'nU0bVIaL',
      'patchouli',
      'Patchouli',
      'Create in-game guidebooks with custom entries and crafting recipes. Used by many popular mods.',
      'Vazkii',
      'required',
      'required',
      37_559_004,
      6_112,
      ['forge', 'utility'],
    ),
    B(
      'Z9OywhE4',
      'pams-harvestcraft-2-food-core',
      "Pam's HarvestCraft 2: Food Core",
      'Adds hundreds of new foods and recipes, making farming and cooking a rich part of survival gameplay.',
      'pamharvestcraft',
      'required',
      'required',
      33_441_298,
      5_877,
      ['forge', 'food'],
    ),
    B(
      'sbJh4AZw',
      'occultism',
      'Occultism',
      'A magic mod about summoning spirits, rituals, and building a personal inter-dimensional storage system.',
      'klikli',
      'required',
      'required',
      29_882_113,
      8_004,
      ['forge', 'magic'],
    ),
    B(
      'OWSRM4vD',
      'cofh-core',
      'CoFH Core',
      'Core library for the CoFH (Thermal Series) family of mods. Required by Thermal Expansion.',
      'TeamCoFH',
      'required',
      'required',
      28_441_003,
      3_219,
      ['forge', 'library'],
    ),
    B(
      'DOSy3C4M',
      'blue-skies',
      'Blue Skies',
      'Two new dimensions — Everbright and Everdawn — filled with unique mobs, structures, and boss encounters.',
      'ModdingLegacy',
      'required',
      'required',
      26_117_445,
      7_334,
      ['forge', 'adventure'],
    ),
    B(
      'fPetb5Kh',
      'natures-compass',
      "Nature's Compass",
      'Locate any biome in the world. Right-click to search and shows distance and coordinates.',
      'Chaosyr',
      'required',
      'optional',
      24_773_992,
      4_118,
      ['forge', 'utility'],
    ),
    B(
      'tpehi7ww',
      'dungeons-and-taverns',
      'Dungeons and Taverns',
      'Replaces vanilla dungeons and adds taverns, towers, and other hand-crafted structures to explore.',
      'NovaWostra',
      'required',
      'required',
      22_334_771,
      6_882,
      ['forge', 'adventure'],
    ),
    B(
      'kidLKymU',
      'yungs-better-strongholds',
      "YUNG's Better Strongholds",
      'A complete redesign of vanilla strongholds. More rooms, better loot, and a more logical layout.',
      'YUNGNICOLAS',
      'required',
      'required',
      20_118_334,
      5_441,
      ['forge', 'adventure'],
    ),
    B(
      'P0Mu4wcQ',
      'artifacts',
      'Artifacts',
      'Adds unique trinkets and baubles scattered throughout the world — each with interesting, powerful effects.',
      'ochotonida',
      'required',
      'required',
      18_772_009,
      6_007,
      ['forge', 'adventure'],
    ),
    B(
      'YyNQVpOu',
      'simple-magnets',
      'Simple Magnets',
      'Adds handheld magnets that attract nearby items and XP orbs. Toggleable and configurable.',
      'svenhjol',
      'required',
      'optional',
      16_334_882,
      3_771,
      ['forge', 'utility'],
    ),
    B(
      '4cJkN3aF',
      'natures-aura',
      "Nature's Aura",
      'Harness the natural aura of the world to power machines and grow magical plants.',
      'Ellpeck',
      'required',
      'required',
      14_008_441,
      4_993,
      ['forge', 'magic'],
    ),
  ],
  total_hits: 20,
  offset: 0,
  limit: 20,
};

// --- Icon enrichment ---
// Called once at startup in demo mode. Fetches real icon_url values from the
// Modrinth API and updates DEMO_MODS and DEMO_BROWSE_RESULTS in-place, correcting
// any extension mismatches (png vs webp) in the hardcoded CDN URLs above.
export async function enrichDemoIcons() {
  const ids = [
    ...DEMO_MODS.filter((m) => m._projectId).map((m) => m._projectId),
    ...DEMO_BROWSE_RESULTS.hits.map((h) => h.project_id),
  ];
  const uniqueIds = [...new Set(ids)];
  if (uniqueIds.length === 0) return;

  const params = new URLSearchParams({ ids: JSON.stringify(uniqueIds) });
  const res = await fetch(`https://api.modrinth.com/v2/projects?${params}`, {
    headers: { 'User-Agent': 'minecraft-manager/1.0 (home-server-panel)', Accept: 'application/json' },
  });
  if (!res.ok) return;

  const projects = await res.json();
  const iconMap = {};
  for (const p of projects) iconMap[p.id] = p.icon_url || null;

  for (const mod of DEMO_MODS) {
    if (mod._projectId && mod._projectId in iconMap) {
      mod.modrinthData.iconUrl = iconMap[mod._projectId];
    }
  }
  for (const hit of DEMO_BROWSE_RESULTS.hits) {
    if (hit.project_id in iconMap) {
      hit.icon_url = iconMap[hit.project_id];
    }
  }
}

// --- Environments (multi-environment demo data) ---
export const DEMO_ENVIRONMENTS = {
  production: {
    name: 'Production',
    serverPath: '/home/minecraft/server',
    minecraftVersion: '1.20.1',
    launch: { executable: 'java', args: ['-Xms2G', '-Xmx8G', 'nogui'] },
    rconHost: '127.0.0.1',
    rconPort: 25575,
    modsFolder: 'mods',
    disabledModsFolder: 'mods_disabled',
    serverAddress: 'play.example.com',
    autoStart: true,
    autoRestart: true,
    tpsAlertThreshold: 18,
    createdAt: '2026-01-15T10:00:00Z',
  },
  staging: {
    name: 'Staging (1.21)',
    serverPath: '/home/minecraft/staging',
    minecraftVersion: '1.21',
    launch: { executable: 'java', args: ['-Xms2G', '-Xmx4G', 'nogui'] },
    rconHost: '127.0.0.1',
    rconPort: 25576,
    modsFolder: 'mods',
    disabledModsFolder: 'mods_disabled',
    serverAddress: 'staging.example.com',
    autoStart: false,
    autoRestart: false,
    tpsAlertThreshold: 18,
    createdAt: '2026-03-01T08:00:00Z',
  },
};

// --- Mod startup statuses (demo) ---
export const DEMO_MOD_STARTUP_STATUSES = {
  'jei-1.20.1-forge-15.20.0.106.jar': { status: 'loaded', messages: [] },
  'create-1.20.1-0.5.1.f.jar': { status: 'loaded', messages: [] },
  'quark-1.20.1-4.0-460.jar': {
    status: 'warning',
    messages: [
      {
        level: 'WARN',
        source: 'quark-zeta',
        text: "Waiting for server start before accepting filewatcher changes to quark's config",
        stackTrace: null,
      },
    ],
  },
  'overweight_farming-1.20.1-1.2.jar': {
    status: 'error',
    messages: [
      {
        level: 'ERROR',
        source: 'ne.mi.co.ForgeHooks',
        text: "Couldn't parse element loot_tables:overweight_farming:blocks/overweight_ginger_block",
        stackTrace: [
          "com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'snowyspirit:ginger'",
          '\tat net.minecraft.util.GsonHelper.m_13866_(GsonHelper.java:145)',
          '\tat java.util.Optional.orElseThrow(Optional.java:403)',
        ],
      },
    ],
  },
};

// --- Panel links (panel user ↔ Minecraft player) ---
export const DEMO_PANEL_LINKS = [
  {
    email: 'admin@example.com',
    minecraftName: 'SteveAdmin',
    linkedBy: 'self:verified',
    verified: true,
    linkedAt: '2026-03-10T14:30:00Z',
  },
  {
    email: 'viewer@example.com',
    minecraftName: 'AlexBuilder',
    linkedBy: 'admin:admin@example.com',
    verified: false,
    linkedAt: '2026-03-12T09:15:00Z',
  },
];
